Update patch set 16
Patch Set 16:

this broke some other tests :
packages/apps/Email/tests/src/com/android/email/provider/AccountBackupRestoreTests.java:65: error: mSyncInterval has private access in Account
        assertEquals(" mSyncInterval", expect.mSyncInterval, actual.mSyncInterval);
                                             ^
packages/apps/Email/tests/src/com/android/email/provider/AccountBackupRestoreTests.java:65: error: mSyncInterval has private access in Account
        assertEquals(" mSyncInterval", expect.mSyncInterval, actual.mSyncInterval);
                                                                   ^
packages/apps/Email/tests/src/com/android/email/provider/ProviderTestUtils.java:57: error: mSyncInterval has private access in Account
        account.mSyncInterval = Account.CHECK_INTERVAL_NEVER;
               ^
packages/apps/Email/tests/src/com/android/email/provider/ProviderTestUtils.java:296: error: mSyncInterval has private access in Account
        assertEquals(caller + " mSyncInterval", expect.mSyncInterval, actual.mSyncInterval);
                                                      ^
packages/apps/Email/tests/src/com/android/email/provider/ProviderTestUtils.java:296: error: mSyncInterval has private access in Account
        assertEquals(caller + " mSyncInterval", expect.mSyncInterval, actual.mSyncInterval);

Patch-set: 16
Reviewer: Kenshin <1220@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0